### ISSUE TITLE
ER Diagrams

### ISSUE THREAD

**Issue by Mertynkk** [festivent/web#4]
ER diagrams that we designed.

**Comment by ugokce** [comment]
Logical ER Diagram
[logical_son.zip](https://github.com/festivent/web/files/1565677/logical_son.zip)

**Comment by Mertynkk** [comment]
[conceptualson.zip](https://github.com/festivent/web/files/1565682/conceptualson.zip)

**Comment by ugokce** [comment]
Physical ER Diagram
[physical_son.zip](https://github.com/festivent/web/files/1565746/physical_son.zip)

**Comment by Mertynkk** [comment]
@anilcancakir

**Comment by ugokce** [comment]
Updated Logical ER Diagram
[logical_sonv2.zip](https://github.com/festivent/web/files/1565749/logical_sonv2.zip)

**Comment by anilcancakir** [comment]
The final diagrams and sql file in this zip.
[festivent.zip](https://github.com/festivent/web/files/1569497/festivent.zip)
